server:
  port: 8081

spring:
  application:
    name: cloud-interfaces-client

eureka:
  client:
    securePortEnabled: true
    ssl:
      key-store: client.p12
      key-store-password: 123456
    serviceUrl:
      defaultZone: https://root:123456@localhost:1000/eureka/